name: CI Pipeline
run-name: ${{ gitea.actor }} is running CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: make
      - make .default-deploy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
